// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview Provides product name suggestions based on user input.
 *
 * - suggestProductNames - A function that suggests product names based on partial input.
 * - SuggestProductNamesInput - The input type for the suggestProductNames function.
 * - SuggestProductNamesOutput - The return type for the suggestProductNames function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestProductNamesInputSchema = z.object({
  partialName: z.string().describe('The partial product name to generate suggestions for.'),
});
export type SuggestProductNamesInput = z.infer<typeof SuggestProductNamesInputSchema>;

const SuggestProductNamesOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('An array of suggested product names.'),
});
export type SuggestProductNamesOutput = z.infer<typeof SuggestProductNamesOutputSchema>;

export async function suggestProductNames(input: SuggestProductNamesInput): Promise<SuggestProductNamesOutput> {
  return suggestProductNamesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestProductNamesPrompt',
  input: {schema: SuggestProductNamesInputSchema},
  output: {schema: SuggestProductNamesOutputSchema},
  prompt: `You are a helpful assistant that provides suggestions for product names based on a partial name.

  Partial Name: {{{partialName}}}

  Provide 5 suggestions for product names that start with the partial name. Return them as a JSON array of strings.`,
});

const suggestProductNamesFlow = ai.defineFlow(
  {
    name: 'suggestProductNamesFlow',
    inputSchema: SuggestProductNamesInputSchema,
    outputSchema: SuggestProductNamesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
